name: Python Application CI/CD Workflow
'on':
  push:
    branches:
    - main
    - master
    - develop
  pull_request:
    branches:
    - main
    - master
    - develop
  workflow_dispatch: {}

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # Optimise la vitesse des lancements suivants

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-mock # Assure que pytest est disponible

    - name: Run Python Tests
      run: |
        pytest tests/
